export const GlobalStyles = {
  fonts: {
    primary: {
      regular: 'SairaStencilOne-Regular',
    },
    secondary: {
      black: 'Raleway-Black',
      blackItalic: 'Raleway-BlackItalic',
      bold: 'Raleway-Bold',
      boldItalic: 'Raleway-BoldItalic',
      extraBold: 'Raleway-ExtraBold',
      extraBoldItalic: 'Raleway-ExtraBoldItalic',
      extraLight: 'Raleway-ExtraLight',
      extraLightItalic: 'Raleway-ExtraLightItalic',
      italic: 'Raleway-Italic',
      light: 'Raleway-Light',
      lightItalic: 'Raleway-LightItalic',
      medium: 'Raleway-Medium',
      mediumItalic: 'Raleway-MediumItalic',
      regular: 'Raleway-Regular',
      semiBold: 'Raleway-SemiBold',
      semiBoldItalic: 'Raleway-SemiBoldItalic',
      thin: 'Raleway-Thin',
      thinItalic: 'Raleway-ThinItalic',
    },
    third: 'Raleway-italic',
  },
  colors: {
    primary: '#8C11BE',
    secondary: '#A328D6',
    third: '#868686',
    light: '#fff',
    dark: '#000',
    positive: '#03AC00',
    negative: '#C70000',
  },
};
